Introduce a new redhat-cloud-client-configuration-cdn binary package
RedHatInsights/redhat-cloud-client-configuration pull request #15
Opened 2024-11-11 10:03 UTC by ptoscano

The existing `redhat-cloud-client-configuration` binary package has a well-defined behaviour when used in cloud images:
- enable the subscription-manager automatic registration
- ensure that there is no content available by default from subscription repositories (and thus keep RHUI as source)

Since soon a different behaviour will be needed, then create a new `redhat-cloud-client-configuration-cdn` binary package to represent that behaviour separately:
- keep enabling the automatic registration
- do not disable the subscription repositories
- ensure to disable the non-public RHEL RHUI repositories:
  - use a "flag file" that soon will be introduced in the RHUI client packages for this
  - use a firstboot script that will disable the repositories; it will run in case `/etc/rhccc-firstboot-run` is there, which will be touch'ed when creating the cloud images with `redhat-cloud-client-configuration-cdn`

Card ID: CCT-701

2025-01-06 15:26 UTC, ptoscano commented
/packit build

2025-01-13 09:08 UTC, m-horky requested changes
In general, the patch looks good. I'd like a clarification on rhcd/yggdrasil handling.

2025-01-13 09:08 UTC, m-horky commented on redhat-cloud-client-configuration.spec
> +%systemd_post rhcd-stop.path
Will those break on newer RHELs where 'rhcd' is 'yggdrasil'?

2025-01-13 09:08 UTC, m-horky commented on redhat-cloud-client-configuration.spec
> +#rhcd
Extreme nitpick: missing space after the hash sign.

2025-01-13 09:08 UTC, m-horky commented on redhat-cloud-client-configuration.spec
> +if [ $1 -eq 0 ]; then
Since you added a comment above

> `# Run following block only during installation (not during update)`

would it be possible to document what this means here as well?

2025-01-14 12:26 UTC, ptoscano commented on redhat-cloud-client-configuration.spec
> +%systemd_post rhcd-stop.path
The `rhc-compat` [1] will take care of that.

[1] https://github.com/RedHatInsights/rhc/pull/144

2025-01-14 12:28 UTC, ptoscano commented on redhat-cloud-client-configuration.spec
> +#rhcd
That's the same as in the `%post` for rhccc; since rhccc-cdn was started as copy/paste from rhccc, then also this came with it.

2025-01-14 12:28 UTC, ptoscano commented on redhat-cloud-client-configuration.spec
> +if [ $1 -eq 0 ]; then
ditto, this came from rhccc

2025-01-14 13:17 UTC, m-horky commented on redhat-cloud-client-configuration.spec
> +#rhcd
Right, but could we have it prettier here, if not there? :)

2025-01-14 13:17 UTC, m-horky commented on redhat-cloud-client-configuration.spec
> +%systemd_post rhcd-stop.path
Would you mind covering that as a comment in there, please?

2025-01-14 13:17 UTC, m-horky commented on redhat-cloud-client-configuration.spec
> +if [ $1 -eq 0 ]; then
...I'd like to see it on both places, then (but changing it just here would be enough for this PR). It's confusing to those who don't have these things memorized.

2025-01-14 14:36 UTC, ptoscano commented on redhat-cloud-client-configuration.spec
> +if [ $1 -eq 0 ]; then
Addressed by #18; once merged, I'll update the copied code here.

2025-01-14 18:11 UTC, m-horky approved these changes
LGTM. Let's wait for QE ack before merging.

2025-01-17 10:55 UTC, Aftermath commented
> LGTM. Let's wait for QE ack before merging.

QE ACK.

2025-01-17 11:11 UTC, merged